# Generated by Django 4.2.25 on 2025-10-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Sensor')),
                ('codigo_serial', models.CharField(max_length=100, unique=True, verbose_name='Código Serial')),
                ('tipo', models.CharField(choices=[('TEMPERATURA', 'Sensor de Temperatura'), ('HUMEDAD', 'Sensor de Humedad'), ('CO2', 'Sensor de CO2'), ('MULTIFUNCION', 'Sensor Multifunción')], max_length=20, verbose_name='Tipo de Sensor')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('ERROR', 'Con Error')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Instalación')),
                ('ultima_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Última Lectura')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fabricante', models.CharField(blank=True, max_length=200, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=200, verbose_name='Modelo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='farms.zona', verbose_name='Zona Asignada')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
