# Generated by Django 4.2.25 on 2025-10-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('AGRONOMO', 'Agrónomo'), ('TECNICO', 'Técnico Agrícola'), ('AGRICULTOR', 'Agricultor')], default='AGRICULTOR', max_length=20, verbose_name='Rol'),
        ),
    ]
