# Generated by Django 4.2.25 on 2025-10-18 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('sensor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(choices=[('TEMPERATURA', 'Temperatura'), ('HUMEDAD', 'Humedad'), ('CO2', 'CO2')], max_length=20, verbose_name='Parámetro')),
                ('valor_minimo', models.FloatField(verbose_name='Valor Mínimo')),
                ('valor_maximo', models.FloatField(verbose_name='Valor Máximo')),
                ('nivel_severidad', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], default='MEDIO', max_length=10, verbose_name='Nivel de Severidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='umbrales_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umbrales', to='farms.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Umbral de Alerta',
                'verbose_name_plural': 'Umbrales de Alerta',
                'ordering': ['zona', 'parametro'],
                'unique_together': {('zona', 'parametro')},
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=20, verbose_name='Parámetro')),
                ('lectura_valor', models.FloatField(verbose_name='Valor de Lectura')),
                ('tipo_alerta', models.CharField(choices=[('EXCESO', 'Exceso'), ('DEFICIENCIA', 'Deficiencia')], max_length=15, verbose_name='Tipo de Alerta')),
                ('nivel_severidad', models.CharField(max_length=10, verbose_name='Nivel de Severidad')),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('LEIDA', 'Leída'), ('RESUELTA', 'Resuelta'), ('IGNORADA', 'Ignorada')], default='NUEVA', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('notificaciones_enviadas', models.JSONField(blank=True, default=dict, verbose_name='Notificaciones Enviadas')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='sensor.sensor', verbose_name='Sensor')),
                ('umbral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='alerts.umbralalerta', verbose_name='Umbral')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='farms.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['-fecha_creacion'], name='alerts_aler_fecha_c_729791_idx'), models.Index(fields=['zona', 'estado'], name='alerts_aler_zona_id_28e2a8_idx')],
            },
        ),
    ]
