# Generated by Django 4.2.25 on 2025-10-18 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
        ('farms', '0001_initial'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='umbralalerta',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='alerta',
            name='alerts_aler_fecha_c_729791_idx',
        ),
        migrations.RemoveIndex(
            model_name='alerta',
            name='alerts_aler_zona_id_28e2a8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='umbralalerta',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='notificaciones_enviadas',
        ),
        migrations.AddField(
            model_name='alerta',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='lectura_valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='nivel_severidad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='parametro',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.sensor'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo_alerta',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='umbral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alerts.umbralalerta'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.zona'),
        ),
        migrations.AlterField(
            model_name='umbralalerta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='umbralalerta',
            name='nivel_severidad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10),
        ),
        migrations.AlterField(
            model_name='umbralalerta',
            name='parametro',
            field=models.CharField(choices=[('TEMPERATURA', 'Temperatura'), ('HUMEDAD', 'Humedad'), ('CO2', 'CO2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='umbralalerta',
            name='valor_maximo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='umbralalerta',
            name='valor_minimo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='umbralalerta',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.zona'),
        ),
        migrations.RemoveField(
            model_name='umbralalerta',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='umbralalerta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='umbralalerta',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='umbralalerta',
            name='notas',
        ),
    ]
