# Generated by Django 4.2.25 on 2025-10-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alerta_options_alter_umbralalerta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='estado',
            field=models.CharField(choices=[('NUEVA', 'Nueva'), ('LEIDA', 'Leída'), ('RESUELTA', 'Resuelta')], default='NUEVA', max_length=10),
        ),
    ]
