# Generated by Django 4.2.25 on 2025-10-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='co2_ppm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
