# Generated by Django 4.2.25 on 2025-10-18 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Finca')),
                ('ubicacion', models.CharField(help_text='Ciudad, provincia o coordenadas', max_length=300, verbose_name='Ubicación')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área Total (hectáreas)')),
                ('cultivo_actual', models.CharField(max_length=200, verbose_name='Cultivo Actual')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas_propias', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('usuarios_asignados', models.ManyToManyField(blank=True, help_text='Usuarios que tienen acceso a esta finca', related_name='fincas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Asignados')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Zona')),
                ('tipo_cultivo', models.CharField(max_length=200, verbose_name='Tipo de Cultivo')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (hectáreas)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('coordenadas', models.JSONField(blank=True, help_text='Coordenadas GPS para mapeo', null=True, verbose_name='Coordenadas')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('PREPARACION', 'En Preparación'), ('COSECHA', 'En Cosecha')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='farms.finca', verbose_name='Finca')),
            ],
            options={
                'verbose_name': 'Zona de Cultivo',
                'verbose_name_plural': 'Zonas de Cultivo',
                'ordering': ['finca', 'nombre'],
                'unique_together': {('finca', 'nombre')},
            },
        ),
    ]
